// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wordsearch.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wordsearch_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wordsearch_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wordsearch_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wordsearch_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wordsearch_2eproto;
class ReqWordSuggest;
struct ReqWordSuggestDefaultTypeInternal;
extern ReqWordSuggestDefaultTypeInternal _ReqWordSuggest_default_instance_;
class RespWordSuggest;
struct RespWordSuggestDefaultTypeInternal;
extern RespWordSuggestDefaultTypeInternal _RespWordSuggest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ReqWordSuggest* Arena::CreateMaybeMessage<::ReqWordSuggest>(Arena*);
template<> ::RespWordSuggest* Arena::CreateMaybeMessage<::RespWordSuggest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ReqWordSuggest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ReqWordSuggest) */ {
 public:
  inline ReqWordSuggest() : ReqWordSuggest(nullptr) {}
  ~ReqWordSuggest() override;
  explicit PROTOBUF_CONSTEXPR ReqWordSuggest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReqWordSuggest(const ReqWordSuggest& from);
  ReqWordSuggest(ReqWordSuggest&& from) noexcept
    : ReqWordSuggest() {
    *this = ::std::move(from);
  }

  inline ReqWordSuggest& operator=(const ReqWordSuggest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqWordSuggest& operator=(ReqWordSuggest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqWordSuggest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqWordSuggest* internal_default_instance() {
    return reinterpret_cast<const ReqWordSuggest*>(
               &_ReqWordSuggest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReqWordSuggest& a, ReqWordSuggest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqWordSuggest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqWordSuggest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqWordSuggest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReqWordSuggest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReqWordSuggest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReqWordSuggest& from) {
    ReqWordSuggest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqWordSuggest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ReqWordSuggest";
  }
  protected:
  explicit ReqWordSuggest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSearchwordFieldNumber = 1,
  };
  // string searchword = 1;
  void clear_searchword();
  const std::string& searchword() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_searchword(ArgT0&& arg0, ArgT... args);
  std::string* mutable_searchword();
  PROTOBUF_NODISCARD std::string* release_searchword();
  void set_allocated_searchword(std::string* searchword);
  private:
  const std::string& _internal_searchword() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_searchword(const std::string& value);
  std::string* _internal_mutable_searchword();
  public:

  // @@protoc_insertion_point(class_scope:ReqWordSuggest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr searchword_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wordsearch_2eproto;
};
// -------------------------------------------------------------------

class RespWordSuggest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RespWordSuggest) */ {
 public:
  inline RespWordSuggest() : RespWordSuggest(nullptr) {}
  ~RespWordSuggest() override;
  explicit PROTOBUF_CONSTEXPR RespWordSuggest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RespWordSuggest(const RespWordSuggest& from);
  RespWordSuggest(RespWordSuggest&& from) noexcept
    : RespWordSuggest() {
    *this = ::std::move(from);
  }

  inline RespWordSuggest& operator=(const RespWordSuggest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespWordSuggest& operator=(RespWordSuggest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespWordSuggest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespWordSuggest* internal_default_instance() {
    return reinterpret_cast<const RespWordSuggest*>(
               &_RespWordSuggest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RespWordSuggest& a, RespWordSuggest& b) {
    a.Swap(&b);
  }
  inline void Swap(RespWordSuggest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespWordSuggest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespWordSuggest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RespWordSuggest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RespWordSuggest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RespWordSuggest& from) {
    RespWordSuggest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RespWordSuggest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RespWordSuggest";
  }
  protected:
  explicit RespWordSuggest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBackwordsFieldNumber = 3,
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // repeated string backwords = 3;
  int backwords_size() const;
  private:
  int _internal_backwords_size() const;
  public:
  void clear_backwords();
  const std::string& backwords(int index) const;
  std::string* mutable_backwords(int index);
  void set_backwords(int index, const std::string& value);
  void set_backwords(int index, std::string&& value);
  void set_backwords(int index, const char* value);
  void set_backwords(int index, const char* value, size_t size);
  std::string* add_backwords();
  void add_backwords(const std::string& value);
  void add_backwords(std::string&& value);
  void add_backwords(const char* value);
  void add_backwords(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& backwords() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_backwords();
  private:
  const std::string& _internal_backwords(int index) const;
  std::string* _internal_add_backwords();
  public:

  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RespWordSuggest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> backwords_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wordsearch_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqWordSuggest

// string searchword = 1;
inline void ReqWordSuggest::clear_searchword() {
  _impl_.searchword_.ClearToEmpty();
}
inline const std::string& ReqWordSuggest::searchword() const {
  // @@protoc_insertion_point(field_get:ReqWordSuggest.searchword)
  return _internal_searchword();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReqWordSuggest::set_searchword(ArgT0&& arg0, ArgT... args) {
 
 _impl_.searchword_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ReqWordSuggest.searchword)
}
inline std::string* ReqWordSuggest::mutable_searchword() {
  std::string* _s = _internal_mutable_searchword();
  // @@protoc_insertion_point(field_mutable:ReqWordSuggest.searchword)
  return _s;
}
inline const std::string& ReqWordSuggest::_internal_searchword() const {
  return _impl_.searchword_.Get();
}
inline void ReqWordSuggest::_internal_set_searchword(const std::string& value) {
  
  _impl_.searchword_.Set(value, GetArenaForAllocation());
}
inline std::string* ReqWordSuggest::_internal_mutable_searchword() {
  
  return _impl_.searchword_.Mutable(GetArenaForAllocation());
}
inline std::string* ReqWordSuggest::release_searchword() {
  // @@protoc_insertion_point(field_release:ReqWordSuggest.searchword)
  return _impl_.searchword_.Release();
}
inline void ReqWordSuggest::set_allocated_searchword(std::string* searchword) {
  if (searchword != nullptr) {
    
  } else {
    
  }
  _impl_.searchword_.SetAllocated(searchword, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.searchword_.IsDefault()) {
    _impl_.searchword_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ReqWordSuggest.searchword)
}

// -------------------------------------------------------------------

// RespWordSuggest

// int32 code = 1;
inline void RespWordSuggest::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t RespWordSuggest::_internal_code() const {
  return _impl_.code_;
}
inline int32_t RespWordSuggest::code() const {
  // @@protoc_insertion_point(field_get:RespWordSuggest.code)
  return _internal_code();
}
inline void RespWordSuggest::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void RespWordSuggest::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:RespWordSuggest.code)
}

// string message = 2;
inline void RespWordSuggest::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& RespWordSuggest::message() const {
  // @@protoc_insertion_point(field_get:RespWordSuggest.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespWordSuggest::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RespWordSuggest.message)
}
inline std::string* RespWordSuggest::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:RespWordSuggest.message)
  return _s;
}
inline const std::string& RespWordSuggest::_internal_message() const {
  return _impl_.message_.Get();
}
inline void RespWordSuggest::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* RespWordSuggest::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* RespWordSuggest::release_message() {
  // @@protoc_insertion_point(field_release:RespWordSuggest.message)
  return _impl_.message_.Release();
}
inline void RespWordSuggest::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RespWordSuggest.message)
}

// repeated string backwords = 3;
inline int RespWordSuggest::_internal_backwords_size() const {
  return _impl_.backwords_.size();
}
inline int RespWordSuggest::backwords_size() const {
  return _internal_backwords_size();
}
inline void RespWordSuggest::clear_backwords() {
  _impl_.backwords_.Clear();
}
inline std::string* RespWordSuggest::add_backwords() {
  std::string* _s = _internal_add_backwords();
  // @@protoc_insertion_point(field_add_mutable:RespWordSuggest.backwords)
  return _s;
}
inline const std::string& RespWordSuggest::_internal_backwords(int index) const {
  return _impl_.backwords_.Get(index);
}
inline const std::string& RespWordSuggest::backwords(int index) const {
  // @@protoc_insertion_point(field_get:RespWordSuggest.backwords)
  return _internal_backwords(index);
}
inline std::string* RespWordSuggest::mutable_backwords(int index) {
  // @@protoc_insertion_point(field_mutable:RespWordSuggest.backwords)
  return _impl_.backwords_.Mutable(index);
}
inline void RespWordSuggest::set_backwords(int index, const std::string& value) {
  _impl_.backwords_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:RespWordSuggest.backwords)
}
inline void RespWordSuggest::set_backwords(int index, std::string&& value) {
  _impl_.backwords_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:RespWordSuggest.backwords)
}
inline void RespWordSuggest::set_backwords(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.backwords_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:RespWordSuggest.backwords)
}
inline void RespWordSuggest::set_backwords(int index, const char* value, size_t size) {
  _impl_.backwords_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:RespWordSuggest.backwords)
}
inline std::string* RespWordSuggest::_internal_add_backwords() {
  return _impl_.backwords_.Add();
}
inline void RespWordSuggest::add_backwords(const std::string& value) {
  _impl_.backwords_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:RespWordSuggest.backwords)
}
inline void RespWordSuggest::add_backwords(std::string&& value) {
  _impl_.backwords_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:RespWordSuggest.backwords)
}
inline void RespWordSuggest::add_backwords(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.backwords_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:RespWordSuggest.backwords)
}
inline void RespWordSuggest::add_backwords(const char* value, size_t size) {
  _impl_.backwords_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:RespWordSuggest.backwords)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
RespWordSuggest::backwords() const {
  // @@protoc_insertion_point(field_list:RespWordSuggest.backwords)
  return _impl_.backwords_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
RespWordSuggest::mutable_backwords() {
  // @@protoc_insertion_point(field_mutable_list:RespWordSuggest.backwords)
  return &_impl_.backwords_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wordsearch_2eproto
