#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "wordsearch.pb.h"

namespace WordSuggestServer
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void WordSuggest(ReqWordSuggest *request, RespWordSuggest *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using WordSuggestDone = std::function<void (RespWordSuggest *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void WordSuggest(const ReqWordSuggest *req, WordSuggestDone done);
	void WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> async_WordSuggest(const ReqWordSuggest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_WordSuggest_task(WordSuggestDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void WordSuggest(const ReqWordSuggest *req, WordSuggestDone done);
	void WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> async_WordSuggest(const ReqWordSuggest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_WordSuggest_task(WordSuggestDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void WordSuggest(const ReqWordSuggest *req, WordSuggestDone done);
	void WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> async_WordSuggest(const ReqWordSuggest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_WordSuggest_task(WordSuggestDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void WordSuggest(const ReqWordSuggest *req, WordSuggestDone done);
	void WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> async_WordSuggest(const ReqWordSuggest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_WordSuggest_task(WordSuggestDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void WordSuggest(const ReqWordSuggest *req, WordSuggestDone done);
	void WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> async_WordSuggest(const ReqWordSuggest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_WordSuggest_task(WordSuggestDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("WordSuggestServer")
{
	this->srpc::RPCService::add_method("WordSuggest",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::WordSuggest);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("WordSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("WordSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::WordSuggest(const ReqWordSuggest *req, WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("WordSuggest", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WordSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> SRPCClient::async_WordSuggest(const ReqWordSuggest *req)
{
	using RESULT = std::pair<RespWordSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespWordSuggest>("WordSuggest", srpc::RPCAsyncFutureCallback<RespWordSuggest>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_WordSuggest_task(WordSuggestDone done)
{
	return this->create_rpc_client_task("WordSuggest", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("WordSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("WordSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::WordSuggest(const ReqWordSuggest *req, WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("WordSuggest", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WordSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> SRPCHttpClient::async_WordSuggest(const ReqWordSuggest *req)
{
	using RESULT = std::pair<RespWordSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespWordSuggest>("WordSuggest", srpc::RPCAsyncFutureCallback<RespWordSuggest>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_WordSuggest_task(WordSuggestDone done)
{
	return this->create_rpc_client_task("WordSuggest", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("WordSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("WordSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::WordSuggest(const ReqWordSuggest *req, WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("WordSuggest", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WordSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> BRPCClient::async_WordSuggest(const ReqWordSuggest *req)
{
	using RESULT = std::pair<RespWordSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespWordSuggest>("WordSuggest", srpc::RPCAsyncFutureCallback<RespWordSuggest>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_WordSuggest_task(WordSuggestDone done)
{
	return this->create_rpc_client_task("WordSuggest", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("WordSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("WordSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::WordSuggest(const ReqWordSuggest *req, WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("/WordSuggestServer/WordSuggest", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WordSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> TRPCClient::async_WordSuggest(const ReqWordSuggest *req)
{
	using RESULT = std::pair<RespWordSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespWordSuggest>("/WordSuggestServer/WordSuggest", srpc::RPCAsyncFutureCallback<RespWordSuggest>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_WordSuggest_task(WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("/WordSuggestServer/WordSuggest", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("WordSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("WordSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::WordSuggest(const ReqWordSuggest *req, WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("WordSuggest", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::WordSuggest(const ReqWordSuggest *req, RespWordSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WordSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespWordSuggest, srpc::RPCSyncContext>> TRPCHttpClient::async_WordSuggest(const ReqWordSuggest *req)
{
	using RESULT = std::pair<RespWordSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespWordSuggest>("WordSuggest", srpc::RPCAsyncFutureCallback<RespWordSuggest>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_WordSuggest_task(WordSuggestDone done)
{
	auto *task = this->create_rpc_client_task("WordSuggest", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace WordSuggestServer

