// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wordsearch.proto

#include "wordsearch.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ReqWordSuggest::ReqWordSuggest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.searchword_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReqWordSuggestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqWordSuggestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqWordSuggestDefaultTypeInternal() {}
  union {
    ReqWordSuggest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqWordSuggestDefaultTypeInternal _ReqWordSuggest_default_instance_;
PROTOBUF_CONSTEXPR RespWordSuggest::RespWordSuggest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.backwords_)*/{}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RespWordSuggestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespWordSuggestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespWordSuggestDefaultTypeInternal() {}
  union {
    RespWordSuggest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespWordSuggestDefaultTypeInternal _RespWordSuggest_default_instance_;
static ::_pb::Metadata file_level_metadata_wordsearch_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_wordsearch_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_wordsearch_2eproto = nullptr;

const uint32_t TableStruct_wordsearch_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ReqWordSuggest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ReqWordSuggest, _impl_.searchword_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RespWordSuggest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::RespWordSuggest, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::RespWordSuggest, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::RespWordSuggest, _impl_.backwords_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ReqWordSuggest)},
  { 7, -1, -1, sizeof(::RespWordSuggest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ReqWordSuggest_default_instance_._instance,
  &::_RespWordSuggest_default_instance_._instance,
};

const char descriptor_table_protodef_wordsearch_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020wordsearch.proto\"$\n\016ReqWordSuggest\022\022\n\n"
  "searchword\030\001 \001(\t\"C\n\017RespWordSuggest\022\014\n\004c"
  "ode\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\021\n\tbackwords\030"
  "\003 \003(\t2G\n\021WordSuggestServer\0222\n\013WordSugges"
  "t\022\017.ReqWordSuggest\032\020.RespWordSuggest\"\000b\006"
  "proto3"
  ;
static ::_pbi::once_flag descriptor_table_wordsearch_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_wordsearch_2eproto = {
    false, false, 206, descriptor_table_protodef_wordsearch_2eproto,
    "wordsearch.proto",
    &descriptor_table_wordsearch_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_wordsearch_2eproto::offsets,
    file_level_metadata_wordsearch_2eproto, file_level_enum_descriptors_wordsearch_2eproto,
    file_level_service_descriptors_wordsearch_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_wordsearch_2eproto_getter() {
  return &descriptor_table_wordsearch_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_wordsearch_2eproto(&descriptor_table_wordsearch_2eproto);

// ===================================================================

class ReqWordSuggest::_Internal {
 public:
};

ReqWordSuggest::ReqWordSuggest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ReqWordSuggest)
}
ReqWordSuggest::ReqWordSuggest(const ReqWordSuggest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReqWordSuggest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.searchword_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.searchword_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.searchword_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_searchword().empty()) {
    _this->_impl_.searchword_.Set(from._internal_searchword(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ReqWordSuggest)
}

inline void ReqWordSuggest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.searchword_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.searchword_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.searchword_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReqWordSuggest::~ReqWordSuggest() {
  // @@protoc_insertion_point(destructor:ReqWordSuggest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReqWordSuggest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.searchword_.Destroy();
}

void ReqWordSuggest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReqWordSuggest::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqWordSuggest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.searchword_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqWordSuggest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string searchword = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_searchword();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ReqWordSuggest.searchword"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReqWordSuggest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReqWordSuggest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string searchword = 1;
  if (!this->_internal_searchword().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_searchword().data(), static_cast<int>(this->_internal_searchword().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ReqWordSuggest.searchword");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_searchword(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReqWordSuggest)
  return target;
}

size_t ReqWordSuggest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ReqWordSuggest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string searchword = 1;
  if (!this->_internal_searchword().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_searchword());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReqWordSuggest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReqWordSuggest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReqWordSuggest::GetClassData() const { return &_class_data_; }


void ReqWordSuggest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReqWordSuggest*>(&to_msg);
  auto& from = static_cast<const ReqWordSuggest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ReqWordSuggest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_searchword().empty()) {
    _this->_internal_set_searchword(from._internal_searchword());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReqWordSuggest::CopyFrom(const ReqWordSuggest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqWordSuggest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqWordSuggest::IsInitialized() const {
  return true;
}

void ReqWordSuggest::InternalSwap(ReqWordSuggest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.searchword_, lhs_arena,
      &other->_impl_.searchword_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqWordSuggest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_wordsearch_2eproto_getter, &descriptor_table_wordsearch_2eproto_once,
      file_level_metadata_wordsearch_2eproto[0]);
}

// ===================================================================

class RespWordSuggest::_Internal {
 public:
};

RespWordSuggest::RespWordSuggest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:RespWordSuggest)
}
RespWordSuggest::RespWordSuggest(const RespWordSuggest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RespWordSuggest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.backwords_){from._impl_.backwords_}
    , decltype(_impl_.message_){}
    , decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.code_ = from._impl_.code_;
  // @@protoc_insertion_point(copy_constructor:RespWordSuggest)
}

inline void RespWordSuggest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.backwords_){arena}
    , decltype(_impl_.message_){}
    , decltype(_impl_.code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RespWordSuggest::~RespWordSuggest() {
  // @@protoc_insertion_point(destructor:RespWordSuggest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RespWordSuggest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.backwords_.~RepeatedPtrField();
  _impl_.message_.Destroy();
}

void RespWordSuggest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RespWordSuggest::Clear() {
// @@protoc_insertion_point(message_clear_start:RespWordSuggest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.backwords_.Clear();
  _impl_.message_.ClearToEmpty();
  _impl_.code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RespWordSuggest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "RespWordSuggest.message"));
        } else
          goto handle_unusual;
        continue;
      // repeated string backwords = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_backwords();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "RespWordSuggest.backwords"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RespWordSuggest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RespWordSuggest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "RespWordSuggest.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // repeated string backwords = 3;
  for (int i = 0, n = this->_internal_backwords_size(); i < n; i++) {
    const auto& s = this->_internal_backwords(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "RespWordSuggest.backwords");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RespWordSuggest)
  return target;
}

size_t RespWordSuggest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RespWordSuggest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string backwords = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.backwords_.size());
  for (int i = 0, n = _impl_.backwords_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.backwords_.Get(i));
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RespWordSuggest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RespWordSuggest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RespWordSuggest::GetClassData() const { return &_class_data_; }


void RespWordSuggest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RespWordSuggest*>(&to_msg);
  auto& from = static_cast<const RespWordSuggest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RespWordSuggest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.backwords_.MergeFrom(from._impl_.backwords_);
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RespWordSuggest::CopyFrom(const RespWordSuggest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RespWordSuggest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespWordSuggest::IsInitialized() const {
  return true;
}

void RespWordSuggest::InternalSwap(RespWordSuggest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.backwords_.InternalSwap(&other->_impl_.backwords_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.code_, other->_impl_.code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RespWordSuggest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_wordsearch_2eproto_getter, &descriptor_table_wordsearch_2eproto_once,
      file_level_metadata_wordsearch_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ReqWordSuggest*
Arena::CreateMaybeMessage< ::ReqWordSuggest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ReqWordSuggest >(arena);
}
template<> PROTOBUF_NOINLINE ::RespWordSuggest*
Arena::CreateMaybeMessage< ::RespWordSuggest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RespWordSuggest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
