// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pagesearch.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pagesearch_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pagesearch_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pagesearch_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pagesearch_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pagesearch_2eproto;
class Item_proto;
struct Item_protoDefaultTypeInternal;
extern Item_protoDefaultTypeInternal _Item_proto_default_instance_;
class ReqPageSuggest;
struct ReqPageSuggestDefaultTypeInternal;
extern ReqPageSuggestDefaultTypeInternal _ReqPageSuggest_default_instance_;
class RespPageSuggest;
struct RespPageSuggestDefaultTypeInternal;
extern RespPageSuggestDefaultTypeInternal _RespPageSuggest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Item_proto* Arena::CreateMaybeMessage<::Item_proto>(Arena*);
template<> ::ReqPageSuggest* Arena::CreateMaybeMessage<::ReqPageSuggest>(Arena*);
template<> ::RespPageSuggest* Arena::CreateMaybeMessage<::RespPageSuggest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Item_proto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Item_proto) */ {
 public:
  inline Item_proto() : Item_proto(nullptr) {}
  ~Item_proto() override;
  explicit PROTOBUF_CONSTEXPR Item_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Item_proto(const Item_proto& from);
  Item_proto(Item_proto&& from) noexcept
    : Item_proto() {
    *this = ::std::move(from);
  }

  inline Item_proto& operator=(const Item_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline Item_proto& operator=(Item_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Item_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const Item_proto* internal_default_instance() {
    return reinterpret_cast<const Item_proto*>(
               &_Item_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Item_proto& a, Item_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(Item_proto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Item_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Item_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Item_proto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Item_proto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Item_proto& from) {
    Item_proto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item_proto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Item_proto";
  }
  protected:
  explicit Item_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 1,
    kLinkFieldNumber = 2,
    kDescriptionFieldNumber = 3,
  };
  // string title = 1;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string link = 2;
  void clear_link();
  const std::string& link() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_link(ArgT0&& arg0, ArgT... args);
  std::string* mutable_link();
  PROTOBUF_NODISCARD std::string* release_link();
  void set_allocated_link(std::string* link);
  private:
  const std::string& _internal_link() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_link(const std::string& value);
  std::string* _internal_mutable_link();
  public:

  // string description = 3;
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // @@protoc_insertion_point(class_scope:Item_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr link_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pagesearch_2eproto;
};
// -------------------------------------------------------------------

class ReqPageSuggest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ReqPageSuggest) */ {
 public:
  inline ReqPageSuggest() : ReqPageSuggest(nullptr) {}
  ~ReqPageSuggest() override;
  explicit PROTOBUF_CONSTEXPR ReqPageSuggest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReqPageSuggest(const ReqPageSuggest& from);
  ReqPageSuggest(ReqPageSuggest&& from) noexcept
    : ReqPageSuggest() {
    *this = ::std::move(from);
  }

  inline ReqPageSuggest& operator=(const ReqPageSuggest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqPageSuggest& operator=(ReqPageSuggest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqPageSuggest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqPageSuggest* internal_default_instance() {
    return reinterpret_cast<const ReqPageSuggest*>(
               &_ReqPageSuggest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ReqPageSuggest& a, ReqPageSuggest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqPageSuggest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqPageSuggest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqPageSuggest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReqPageSuggest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReqPageSuggest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReqPageSuggest& from) {
    ReqPageSuggest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqPageSuggest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ReqPageSuggest";
  }
  protected:
  explicit ReqPageSuggest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSearchstringFieldNumber = 1,
  };
  // string searchstring = 1;
  void clear_searchstring();
  const std::string& searchstring() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_searchstring(ArgT0&& arg0, ArgT... args);
  std::string* mutable_searchstring();
  PROTOBUF_NODISCARD std::string* release_searchstring();
  void set_allocated_searchstring(std::string* searchstring);
  private:
  const std::string& _internal_searchstring() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_searchstring(const std::string& value);
  std::string* _internal_mutable_searchstring();
  public:

  // @@protoc_insertion_point(class_scope:ReqPageSuggest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr searchstring_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pagesearch_2eproto;
};
// -------------------------------------------------------------------

class RespPageSuggest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RespPageSuggest) */ {
 public:
  inline RespPageSuggest() : RespPageSuggest(nullptr) {}
  ~RespPageSuggest() override;
  explicit PROTOBUF_CONSTEXPR RespPageSuggest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RespPageSuggest(const RespPageSuggest& from);
  RespPageSuggest(RespPageSuggest&& from) noexcept
    : RespPageSuggest() {
    *this = ::std::move(from);
  }

  inline RespPageSuggest& operator=(const RespPageSuggest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespPageSuggest& operator=(RespPageSuggest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespPageSuggest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespPageSuggest* internal_default_instance() {
    return reinterpret_cast<const RespPageSuggest*>(
               &_RespPageSuggest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RespPageSuggest& a, RespPageSuggest& b) {
    a.Swap(&b);
  }
  inline void Swap(RespPageSuggest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespPageSuggest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespPageSuggest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RespPageSuggest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RespPageSuggest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RespPageSuggest& from) {
    RespPageSuggest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RespPageSuggest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RespPageSuggest";
  }
  protected:
  explicit RespPageSuggest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemprotoFieldNumber = 3,
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // repeated .Item_proto itemproto = 3;
  int itemproto_size() const;
  private:
  int _internal_itemproto_size() const;
  public:
  void clear_itemproto();
  ::Item_proto* mutable_itemproto(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Item_proto >*
      mutable_itemproto();
  private:
  const ::Item_proto& _internal_itemproto(int index) const;
  ::Item_proto* _internal_add_itemproto();
  public:
  const ::Item_proto& itemproto(int index) const;
  ::Item_proto* add_itemproto();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Item_proto >&
      itemproto() const;

  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RespPageSuggest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Item_proto > itemproto_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int32_t code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pagesearch_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Item_proto

// string title = 1;
inline void Item_proto::clear_title() {
  _impl_.title_.ClearToEmpty();
}
inline const std::string& Item_proto::title() const {
  // @@protoc_insertion_point(field_get:Item_proto.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Item_proto::set_title(ArgT0&& arg0, ArgT... args) {
 
 _impl_.title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Item_proto.title)
}
inline std::string* Item_proto::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:Item_proto.title)
  return _s;
}
inline const std::string& Item_proto::_internal_title() const {
  return _impl_.title_.Get();
}
inline void Item_proto::_internal_set_title(const std::string& value) {
  
  _impl_.title_.Set(value, GetArenaForAllocation());
}
inline std::string* Item_proto::_internal_mutable_title() {
  
  return _impl_.title_.Mutable(GetArenaForAllocation());
}
inline std::string* Item_proto::release_title() {
  // @@protoc_insertion_point(field_release:Item_proto.title)
  return _impl_.title_.Release();
}
inline void Item_proto::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  _impl_.title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Item_proto.title)
}

// string link = 2;
inline void Item_proto::clear_link() {
  _impl_.link_.ClearToEmpty();
}
inline const std::string& Item_proto::link() const {
  // @@protoc_insertion_point(field_get:Item_proto.link)
  return _internal_link();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Item_proto::set_link(ArgT0&& arg0, ArgT... args) {
 
 _impl_.link_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Item_proto.link)
}
inline std::string* Item_proto::mutable_link() {
  std::string* _s = _internal_mutable_link();
  // @@protoc_insertion_point(field_mutable:Item_proto.link)
  return _s;
}
inline const std::string& Item_proto::_internal_link() const {
  return _impl_.link_.Get();
}
inline void Item_proto::_internal_set_link(const std::string& value) {
  
  _impl_.link_.Set(value, GetArenaForAllocation());
}
inline std::string* Item_proto::_internal_mutable_link() {
  
  return _impl_.link_.Mutable(GetArenaForAllocation());
}
inline std::string* Item_proto::release_link() {
  // @@protoc_insertion_point(field_release:Item_proto.link)
  return _impl_.link_.Release();
}
inline void Item_proto::set_allocated_link(std::string* link) {
  if (link != nullptr) {
    
  } else {
    
  }
  _impl_.link_.SetAllocated(link, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.link_.IsDefault()) {
    _impl_.link_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Item_proto.link)
}

// string description = 3;
inline void Item_proto::clear_description() {
  _impl_.description_.ClearToEmpty();
}
inline const std::string& Item_proto::description() const {
  // @@protoc_insertion_point(field_get:Item_proto.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Item_proto::set_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Item_proto.description)
}
inline std::string* Item_proto::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:Item_proto.description)
  return _s;
}
inline const std::string& Item_proto::_internal_description() const {
  return _impl_.description_.Get();
}
inline void Item_proto::_internal_set_description(const std::string& value) {
  
  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* Item_proto::_internal_mutable_description() {
  
  return _impl_.description_.Mutable(GetArenaForAllocation());
}
inline std::string* Item_proto::release_description() {
  // @@protoc_insertion_point(field_release:Item_proto.description)
  return _impl_.description_.Release();
}
inline void Item_proto::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  _impl_.description_.SetAllocated(description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Item_proto.description)
}

// -------------------------------------------------------------------

// ReqPageSuggest

// string searchstring = 1;
inline void ReqPageSuggest::clear_searchstring() {
  _impl_.searchstring_.ClearToEmpty();
}
inline const std::string& ReqPageSuggest::searchstring() const {
  // @@protoc_insertion_point(field_get:ReqPageSuggest.searchstring)
  return _internal_searchstring();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReqPageSuggest::set_searchstring(ArgT0&& arg0, ArgT... args) {
 
 _impl_.searchstring_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ReqPageSuggest.searchstring)
}
inline std::string* ReqPageSuggest::mutable_searchstring() {
  std::string* _s = _internal_mutable_searchstring();
  // @@protoc_insertion_point(field_mutable:ReqPageSuggest.searchstring)
  return _s;
}
inline const std::string& ReqPageSuggest::_internal_searchstring() const {
  return _impl_.searchstring_.Get();
}
inline void ReqPageSuggest::_internal_set_searchstring(const std::string& value) {
  
  _impl_.searchstring_.Set(value, GetArenaForAllocation());
}
inline std::string* ReqPageSuggest::_internal_mutable_searchstring() {
  
  return _impl_.searchstring_.Mutable(GetArenaForAllocation());
}
inline std::string* ReqPageSuggest::release_searchstring() {
  // @@protoc_insertion_point(field_release:ReqPageSuggest.searchstring)
  return _impl_.searchstring_.Release();
}
inline void ReqPageSuggest::set_allocated_searchstring(std::string* searchstring) {
  if (searchstring != nullptr) {
    
  } else {
    
  }
  _impl_.searchstring_.SetAllocated(searchstring, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.searchstring_.IsDefault()) {
    _impl_.searchstring_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ReqPageSuggest.searchstring)
}

// -------------------------------------------------------------------

// RespPageSuggest

// int32 code = 1;
inline void RespPageSuggest::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t RespPageSuggest::_internal_code() const {
  return _impl_.code_;
}
inline int32_t RespPageSuggest::code() const {
  // @@protoc_insertion_point(field_get:RespPageSuggest.code)
  return _internal_code();
}
inline void RespPageSuggest::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void RespPageSuggest::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:RespPageSuggest.code)
}

// string message = 2;
inline void RespPageSuggest::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& RespPageSuggest::message() const {
  // @@protoc_insertion_point(field_get:RespPageSuggest.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespPageSuggest::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RespPageSuggest.message)
}
inline std::string* RespPageSuggest::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:RespPageSuggest.message)
  return _s;
}
inline const std::string& RespPageSuggest::_internal_message() const {
  return _impl_.message_.Get();
}
inline void RespPageSuggest::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* RespPageSuggest::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* RespPageSuggest::release_message() {
  // @@protoc_insertion_point(field_release:RespPageSuggest.message)
  return _impl_.message_.Release();
}
inline void RespPageSuggest::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RespPageSuggest.message)
}

// repeated .Item_proto itemproto = 3;
inline int RespPageSuggest::_internal_itemproto_size() const {
  return _impl_.itemproto_.size();
}
inline int RespPageSuggest::itemproto_size() const {
  return _internal_itemproto_size();
}
inline void RespPageSuggest::clear_itemproto() {
  _impl_.itemproto_.Clear();
}
inline ::Item_proto* RespPageSuggest::mutable_itemproto(int index) {
  // @@protoc_insertion_point(field_mutable:RespPageSuggest.itemproto)
  return _impl_.itemproto_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Item_proto >*
RespPageSuggest::mutable_itemproto() {
  // @@protoc_insertion_point(field_mutable_list:RespPageSuggest.itemproto)
  return &_impl_.itemproto_;
}
inline const ::Item_proto& RespPageSuggest::_internal_itemproto(int index) const {
  return _impl_.itemproto_.Get(index);
}
inline const ::Item_proto& RespPageSuggest::itemproto(int index) const {
  // @@protoc_insertion_point(field_get:RespPageSuggest.itemproto)
  return _internal_itemproto(index);
}
inline ::Item_proto* RespPageSuggest::_internal_add_itemproto() {
  return _impl_.itemproto_.Add();
}
inline ::Item_proto* RespPageSuggest::add_itemproto() {
  ::Item_proto* _add = _internal_add_itemproto();
  // @@protoc_insertion_point(field_add:RespPageSuggest.itemproto)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Item_proto >&
RespPageSuggest::itemproto() const {
  // @@protoc_insertion_point(field_list:RespPageSuggest.itemproto)
  return _impl_.itemproto_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pagesearch_2eproto
