#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "pagesearch.pb.h"

namespace PageSuggestServer
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void PageSuggest(ReqPageSuggest *request, RespPageSuggest *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using PageSuggestDone = std::function<void (RespPageSuggest *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void PageSuggest(const ReqPageSuggest *req, PageSuggestDone done);
	void PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> async_PageSuggest(const ReqPageSuggest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_PageSuggest_task(PageSuggestDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void PageSuggest(const ReqPageSuggest *req, PageSuggestDone done);
	void PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> async_PageSuggest(const ReqPageSuggest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_PageSuggest_task(PageSuggestDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void PageSuggest(const ReqPageSuggest *req, PageSuggestDone done);
	void PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> async_PageSuggest(const ReqPageSuggest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_PageSuggest_task(PageSuggestDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void PageSuggest(const ReqPageSuggest *req, PageSuggestDone done);
	void PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> async_PageSuggest(const ReqPageSuggest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_PageSuggest_task(PageSuggestDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void PageSuggest(const ReqPageSuggest *req, PageSuggestDone done);
	void PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> async_PageSuggest(const ReqPageSuggest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_PageSuggest_task(PageSuggestDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("PageSuggestServer")
{
	this->srpc::RPCService::add_method("PageSuggest",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::PageSuggest);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("PageSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("PageSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::PageSuggest(const ReqPageSuggest *req, PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("PageSuggest", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_PageSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> SRPCClient::async_PageSuggest(const ReqPageSuggest *req)
{
	using RESULT = std::pair<RespPageSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespPageSuggest>("PageSuggest", srpc::RPCAsyncFutureCallback<RespPageSuggest>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_PageSuggest_task(PageSuggestDone done)
{
	return this->create_rpc_client_task("PageSuggest", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("PageSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("PageSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::PageSuggest(const ReqPageSuggest *req, PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("PageSuggest", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_PageSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> SRPCHttpClient::async_PageSuggest(const ReqPageSuggest *req)
{
	using RESULT = std::pair<RespPageSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespPageSuggest>("PageSuggest", srpc::RPCAsyncFutureCallback<RespPageSuggest>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_PageSuggest_task(PageSuggestDone done)
{
	return this->create_rpc_client_task("PageSuggest", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("PageSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("PageSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::PageSuggest(const ReqPageSuggest *req, PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("PageSuggest", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_PageSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> BRPCClient::async_PageSuggest(const ReqPageSuggest *req)
{
	using RESULT = std::pair<RespPageSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespPageSuggest>("PageSuggest", srpc::RPCAsyncFutureCallback<RespPageSuggest>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_PageSuggest_task(PageSuggestDone done)
{
	return this->create_rpc_client_task("PageSuggest", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("PageSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("PageSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::PageSuggest(const ReqPageSuggest *req, PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("/PageSuggestServer/PageSuggest", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_PageSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> TRPCClient::async_PageSuggest(const ReqPageSuggest *req)
{
	using RESULT = std::pair<RespPageSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespPageSuggest>("/PageSuggestServer/PageSuggest", srpc::RPCAsyncFutureCallback<RespPageSuggest>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_PageSuggest_task(PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("/PageSuggestServer/PageSuggest", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("PageSuggestServer")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("PageSuggestServer")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::PageSuggest(const ReqPageSuggest *req, PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("PageSuggest", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::PageSuggest(const ReqPageSuggest *req, RespPageSuggest *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_PageSuggest(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<RespPageSuggest, srpc::RPCSyncContext>> TRPCHttpClient::async_PageSuggest(const ReqPageSuggest *req)
{
	using RESULT = std::pair<RespPageSuggest, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<RespPageSuggest>("PageSuggest", srpc::RPCAsyncFutureCallback<RespPageSuggest>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_PageSuggest_task(PageSuggestDone done)
{
	auto *task = this->create_rpc_client_task("PageSuggest", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace PageSuggestServer

